version: '3.3'

networks:
  ilakhtenkov_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

services:
  mongodb:
    image: mongo
    container_name: mongo
    networks:
      ilakhtenkov_net:
        ipv4_address: 172.16.0.20
    ports:
      - 27017:27017


